### ISSUE TITLE
Updates broken due to new Web IDL constructor syntax

### ISSUE THREAD

**Issue by foolip** [foolip/bikeshed-tests#9]
https://travis-ci.com/foolip/bikeshed-tests/builds/125195278 has begun failing at the `bikeshed test --rebase` step, like this:
```
 (cd tests; find github -type f) | xargs bikeshed test --rebase
  1/336: Rebasing github/heycam/webidl/index.bs
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.15/bin/bikeshed", line 11, in <module>
    load_entry_point('Bikeshed', 'console_scripts', 'bikeshed')()
  File "/home/travis/build/foolip/bikeshed-tests/bikeshed/bikeshed/cli.py", line 221, in main
    handleTest(options, extras)
  File "/home/travis/build/foolip/bikeshed-tests/bikeshed/bikeshed/cli.py", line 369, in handleTest
    test.rebase(Spec, options.testFiles, md=md)
  File "/home/travis/build/foolip/bikeshed-tests/bikeshed/bikeshed/test.py", line 125, in rebase
    doc.preprocess()
  File "/home/travis/build/foolip/bikeshed-tests/bikeshed/bikeshed/Spec.py", line 103, in preprocess
    self.processDocument()
  File "/home/travis/build/foolip/bikeshed-tests/bikeshed/bikeshed/Spec.py", line 186, in processDocument
    idl.markupIDL(self)
  File "/home/travis/build/foolip/bikeshed-tests/bikeshed/bikeshed/idl.py", line 231, in markupIDL
    replaceContents(el, parseHTML(unicode(widl.markup(marker))))
  File "/home/travis/build/foolip/bikeshed-tests/bikeshed/bikeshed/widlparser/widlparser/parser.py", line 280, in markup
    return generator.markup(marker)
  File "/home/travis/build/foolip/bikeshed-tests/bikeshed/bikeshed/widlparser/widlparser/markup.py", line 81, in markup
    output += u''.join([child.markup(marker, self.construct) for child in self.children])
  File "/home/travis/build/foolip/bikeshed-tests/bikeshed/bikeshed/widlparser/widlparser/markup.py", line 81, in markup
    output += u''.join([child.markup(marker, self.construct) for child in self.children])
  File "/home/travis/build/foolip/bikeshed-tests/bikeshed/bikeshed/widlparser/widlparser/markup.py", line 81, in markup
    output += u''.join([child.markup(marker, self.construct) for child in self.children])
  File "/home/travis/build/foolip/bikeshed-tests/bikeshed/bikeshed/widlparser/widlparser/markup.py", line 81, in markup
    output += u''.join([child.markup(marker, self.construct) for child in self.children])
  File "/home/travis/build/foolip/bikeshed-tests/bikeshed/bikeshed/widlparser/widlparser/markup.py", line 164, in markup
    head, tail = marker.markupName(self.text, construct) if (hasattr(marker, 'markupName')) else (None, None)
  File "/home/travis/build/foolip/bikeshed-tests/bikeshed/bikeshed/idl.py", line 168, in markupName
    methodNames = ["{0}/{1}".format(interfaceName, m) for m in construct.parent.methodNames]
  File "/home/travis/build/foolip/bikeshed-tests/bikeshed/bikeshed/widlparser/widlparser/productions.py", line 1799, in methodNames
    return [_name(self) + '(' + argumentName + ')' for argumentName in self.arguments.argumentNames]
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

I'm pretty sure that's because https://github.com/heycam/webidl/pull/780 landed.

**Comment by foolip** [comment]
Should be fixed by https://github.com/tabatkins/bikeshed/pull/1514.
